# -*- coding: utf-8 -*-
"""DL_SentimentAnalysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wmtsYFeccBzYTrJgm9Kvwe9sCcf6OiRZ

# Step 1: Environment Setup
installing required libraries like pandas for data loading and manipulation, numpy for matrix calculations, matplotlib for data visualization, scikit-learn for using pretrained models, tensorflow for building, training, and deploying deep learning models

# Step 2: Importing necessary libraries and packages
"""

# Importing necessary libraries
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout, Input, Bidirectional
from sklearn.utils.class_weight import compute_class_weight
from tensorflow.keras.callbacks import EarlyStopping

# Loading and inspecting dataset
df = pd.read_csv('/content/Job_3_Resource_sentiment.csv')

"""# Step 3: Loading and Inspecting Dataset
We see the information, overview, rows and columns present in the data. Also we look at the missing values if present.
"""

df.head()

df.info()

df.columns

df.rename(columns={'Positive':'sentiment'}, inplace=True)
# inplace=True: Modifies the original object (e.g., a DataFrame) and typically returns None.

df.rename(columns={'im getting on borderlands and i will murder you all ,':'text'}, inplace=True)
#

"""# Step 4: Data Cleaning
We drop the missing values if the number of missing data is negligible or we fill it up with the average or mean values if the data is not negligible. Also we drop any unnecessary columns.
"""

df.isnull().sum()

df.drop(columns=['2401','Borderlands'])

df['text'] = df['text'].astype(str)

def clean_text(text):
    text = text.lower()
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"[^a-z\s]", "", text)
    return text.strip()

df['text'] = df['text'].apply(clean_text)

df['text'].head()

"""# Step 5: Encode Target Labels
We encode target labels because most machine learning models operate on numerical data, not raw categorical strings; converting labels into numbers allows algorithms to compute loss, gradients, and predictions efficiently while preserving class distinctions. The choice of encoding depends on the problem: for classification, we often use integer encoding (e.g., via LabelEncoder) or one-hot encoding (e.g., OneHotEncoder or pd.get_dummies) to avoid implying ordinal relationships between classes; for binary labels, simple 0/1 mapping is common; and for neural networks, one-hot vectors or even embeddings may be used depending on complexity. In Python, typical approaches include from sklearn.preprocessing import LabelEncoder, OneHotEncoder, using LabelEncoder().fit_transform(y) for integer labels, or OneHotEncoder(sparse_output=False).fit_transform(y.reshape(-1,1)), and in pandas pd.get_dummies(y)—each ensuring the model receives a mathematically usable representation of the targets.
"""

# Encode the target column
le = LabelEncoder()
df['sentiment_encoded'] = le.fit_transform(df['sentiment'])

print("Label mapping:")
for i, c in enumerate(le.classes_):
    print(i, "->", c)

df.sample(5)

"""# Step 6: Text Tokenization and Padding
We perform text tokenization and padding because raw text is unstructured and variable in length, while machine learning models—especially neural networks—require fixed-size numerical inputs. Tokenization converts text into discrete units (words, subwords, or characters) and maps them to integers so models can process semantic patterns, while padding ensures all sequences have the same length by adding special tokens (usually zeros) to shorter sequences, enabling efficient batch processing without shape mismatches. In Python, this is commonly done using Keras utilities like Tokenizer() to build a vocabulary and convert text via texts_to_sequences(), followed by pad_sequences(sequences, maxlen=..., padding='post'); in modern NLP pipelines (e.g., Hugging Face Transformers), tokenizers handle both steps together using methods like tokenizer(texts, padding=True, truncation=True, return_tensors="pt"), producing uniform tensor inputs ready for models.
"""

# Tokenizer
tokenizer = Tokenizer(num_words = 10000, oov_token='<OOV>')
tokenizer.fit_on_texts(df['text'])


seq = tokenizer.texts_to_sequences(df['text'])

# Padding

max_length = 100
X = pad_sequences(seq, maxlen=max_length, padding='post', truncating='post')

y = df['sentiment_encoded'].values

X

y

"""# Step 7: Train/ Validation / Test Split
We split data into train, validation, and test sets to get an unbiased estimate of how well a model will generalize to unseen data and to avoid overfitting during development. The training set is used to learn model parameters, the validation set is used during tuning (e.g., hyperparameters, model selection, early stopping) so we don’t indirectly “peek” at the test data, and the test set is held out until the very end to provide a final, honest evaluation; without this separation, performance metrics can become overly optimistic because the model (or the human tuning it) has effectively memorized patterns specific to the dataset. In Python, this is typically done with from sklearn.model_selection import train_test_split, e.g., first splitting into train+temp and test, then splitting temp into validation (X_train, X_temp, y_train, y_temp = train_test_split(..., test_size=0.3); X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5)), ensuring each subset remains statistically representative.
"""

# Train Test Splitting

X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3, random_state=42)

X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

# This code performs a two-stage split to divide a dataset (X,y) into three distinct sets—Train (70%), Validation (15%), and Test (15%)—using scikit-learn. It ensures reproducible shuffling (random_state=42). This method prepares data for training, hyperparameter tuning (validation), and final evaluation
print("Train:",X_train.shape, y_train.shape)
print("Validation:",X_val.shape, y_val.shape)
print("Test:",X_test.shape, y_test.shape)

# Bias handling(class weights)
class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train),
    y=y_train
)

class_weights_dict = dict(enumerate(class_weights))
print("\nClass Weights:", class_weights_dict)

"""# Step 8: Choosing Learning Model: LSTM
We choose an LSTM (Long Short-Term Memory) model when the task involves sequential or time-dependent data—like text, time series, or speech—because it can retain and use information from earlier steps in a sequence, something standard feedforward networks cannot do. Unlike basic RNNs, LSTMs address the vanishing gradient problem by using gated mechanisms (input, forget, and output gates) that control what information is kept, updated, or discarded, allowing the model to learn long-range dependencies (e.g., understanding context across a sentence). This makes LSTMs especially useful in NLP tasks such as sentiment analysis or language modeling, where word order and context matter. In Python, using Keras, you typically define it as model.add(LSTM(units, return_sequences=...)) within a sequential model, often preceded by an Embedding layer and followed by dense layers for prediction, enabling the network to learn meaningful patterns from tokenized and padded sequences.
"""

max_words = 10000

# LSTM
model = Sequential([
    Input(shape=(max_length,)),
    Embedding(max_words, 128),
    Bidirectional(LSTM(64)),
    Dropout(0.5),
    Dense(4, activation='softmax')
])

model.summary()

"""# Step 9: Compiling Model
We compile a model to specify exactly how it should learn before training begins—this step binds together the loss function (what error to minimize), the optimizer (how weights are updated), and evaluation metrics (how performance is tracked). Without compilation, the model has an architecture but no defined training logic, so it cannot compute gradients or update parameters. The loss function depends on the task (e.g., binary_crossentropy for binary classification, categorical_crossentropy for multi-class), the optimizer (like Adam or SGD) controls the learning dynamics, and metrics (like accuracy) provide interpretable feedback during training. In Python, using Keras, this is done with model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy']), which prepares the model internally for efficient forward and backward passes during model.fit().
"""

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

"""# Step 10: Training Model
We train the model to actually learn patterns from data by adjusting its internal parameters (weights) so that predictions get closer to the true labels. Up to this point, the model is just a structure with randomly initialized weights; during training, it performs forward passes to make predictions, computes error using the loss function, and then uses backpropagation with an optimizer to update weights iteratively over many epochs. This process allows the model to capture relationships in the data (e.g., sequence patterns in text for an LSTM) rather than guessing randomly. In Python, using Keras, training is done with model.fit(X_train, y_train, validation_data=(X_val, y_val), epochs=..., batch_size=...), where the validation set helps monitor generalization and detect overfitting during the learning process.
"""

early = EarlyStopping(patience=3, restore_best_weights=True)

history = model.fit(
    X_train, y_train,
    epochs=20,
    batch_size=32,
    validation_data=(X_val, y_val),
    callbacks=[early],
    class_weight=class_weights_dict
)

"""# Step 11: Visualize Performance
We visualize model performance to diagnose how learning is progressing and detect issues that raw metrics alone can hide, such as overfitting, underfitting, or unstable training. By plotting training vs. validation loss and accuracy over epochs, you can see patterns—e.g., training loss decreasing while validation loss increases (overfitting), or both staying high (underfitting)—which directly informs decisions like adjusting model complexity, learning rate, or regularization. Visualization also helps verify whether training has converged or if more epochs are needed. In Python, this is typically done by capturing the history from model.fit() in Keras and plotting it using matplotlib, e.g., history.history['loss'] and history.history['val_loss'], giving a clear, interpretable view of model behavior over time.

"""

plt.figure(figsize=(12,5))

# Accuracy
plt.subplot(1,2,1)
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.legend()
plt.title("Accuracy Curve")

# Loss
plt.subplot(1,2,2)
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.legend()
plt.title("Loss Curve")

plt.show()

"""# Step 12: Generalization Checking
We perform this step to evaluate whether the model has learned the right level of complexity—not just memorized the training data (overfitting) or failed to learn meaningful patterns at all (underfitting). A model that looks “accurate” on training data can still fail in real use if it doesn’t generalize, so detecting these conditions helps you decide what to fix: overfitting suggests adding regularization, more data, or simplifying the model, while underfitting points to increasing model capacity, training longer, or improving features. This step acts as a diagnostic checkpoint between training and deployment, ensuring the model’s performance is both strong and reliable, rather than misleading due to poor generalization.
"""

if history.history['accuracy'][-1] > history.history['val_accuracy'][-1]:
    print("⚠️ Possible Overfitting detected")
else:
    print("✅ Model is generalizing well")

"""# Step 13: Model Evaluation and saving
We perform model evaluation and saving to finalize and preserve a reliable version of the model after training. Evaluation uses the untouched test set to provide an unbiased estimate of real-world performance, confirming that the model generalizes beyond the data it was trained and tuned on; without this step, reported accuracy can be misleading. Saving the model then ensures that this validated state—its architecture, learned weights, and sometimes preprocessing steps—can be reused without retraining, which is critical for deployment, reproducibility, and future inference. In Python, using Keras, evaluation is done with model.evaluate(X_test, y_test), and saving with model.save("model.h5") (or the newer .keras format), allowing you to later reload it via load_model() and use it directly for predictions.
"""

# Evaluation
y_pred = np.argmax(model.predict(X_test), axis=1)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

# Save Model
model.save("sentiment_analysis_model.keras")
print("✅ Model saved successfully")

# Testing with new Text
def predict_sentiment(text):
    seq = tokenizer.texts_to_sequences([text])
    pad = pad_sequences(seq, maxlen=100, padding='post')
    probs = model.predict(pad)[0]
    return le.classes_[probs.argmax()], probs

texts = [
    "I love this game so much",
    "This game is terrible",
    "I have no opinion",
    "What is this even about?",
    "the game was bad",
    "Taurat didn't think good of the game"
]

for t in texts:
    pred, prob = predict_sentiment(t)
    print(t, "->", pred)

